# Project information

site_name: Secrets Manager Builder Sessions
site_description: 'A collection of hands-on Builder Sesssions to learn about using Secrets Manager.'
site_author: 'aws-security-workshops@amazon.com'
site_url: 'https://secrets-manager.awssecworkshops.com/'

# Repository
repo_name: 'aws-samples/aws-secretsmgr-workshop'
repo_url: 'https://github.com/aws-samples/aws-secretsmgr-workshop'

# Copyright
copyright: '<a href="https://aws.amazon.com/privacy/" target="_blank">Privacy</a> | <a href="https://aws.amazon.com/terms/" target="_blank">Site terms</a> | &copy; 2020, Amazon Web Services, Inc. or its affiliates. All rights reserved.'

# Configuration
theme:
  name: 'material'
  logo: 'assets/images/aws_smile_logo.png'
  favicon: 'assets/images/aws-favicon.ico'
  features:
    - tabs

# Customization
extra_css:
  - 'stylesheets/custom.css'
extra:
  social:
    - icon: fontawesome/solid/home
      link: https://awssecworkshops.com
    - icon: fontawesome/solid/shield-alt
      link: https://aws.amazon.com/security/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/awssecurityinfo?lang=en
    - icon: fontawesome/solid/rss-square
      link: https://aws.amazon.com/blogs/security/

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details

# Navigation
nav:
  - Overview: 'index.md'
  - 'RDS and Fargate':
    - 'Scenario': 'RDSFargate/index.md'
    - 'Build phase': 'RDSFargate/build.md'
    - 'RDS phase': 'RDSFargate/RDS.md'
    - 'Fargate phase': 'RDSFargate/Fargate.md'
    - 'Clean up phase': 'RDSFargate/cleanup.md'
  - 'Contributing': 'contribute.md'
  - 'License': 'https://github.com/aws-samples/aws-secretsmgr-workshop/blob/master/LICENSE'
